---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world test
  - openapi-cli -spec ./oosa-specification.yml -output ./output.json
  - cat ./output.json